services:

  mongodb:
    image: mongo:7.0.34-jammy
    container_name: mongodb
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    healthcheck:
      test: >
        mongosh --quiet --eval
        'try { rs.status().ok } catch (e) { rs.initiate({_id: "rs0", members: [{ _id: 0, host: "mongodb:27017" }] }).ok }'
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4.3.0-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
  
  ibmmq:
    image: jan310/ibm-mqadvanced-server-dev:9.4.5.1-arm64
    container_name: ibmmq
    ports:
      - "1414:1414"   # IBM MQ
      - "9443:9443"   # Management UI (via https)
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
      MQ_APP_PASSWORD: ${IBM_MQ_PASSWORD} # user = app
      MQ_ADMIN_PASSWORD: ${IBM_MQ_PASSWORD} # user = admin
    volumes:
      - ./config.mqsc:/etc/mqm/config.mqsc

  vedoc:
    build:
      context: ./vedoc
    container_name: vedoc
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: web
      SPRING_MONGODB_URI: mongodb://mongodb:27017/vedoc?replicaSet=rs0
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  xml-json-adapter:
    build:
      context: ./xml-json-adapter
    container_name: xml-json-adapter
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      IBM_MQ_QUEUE_MANAGER: QM1
      IBM_MQ_CONN_NAME: ibmmq(1414)
      IBM_MQ_CHANNEL: DEV.APP.SVRCONN
      IBM_MQ_USER: ${IBM_MQ_USER:-app}
      IBM_MQ_PASSWORD: ${IBM_MQ_PASSWORD}
    depends_on:
      rabbitmq:
        condition: service_started
      ibmmq:
        condition: service_started
      vedoc:
        condition: service_started
