services:

  mongodb:
    image: mongo:7.0.34-jammy
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

  rabbitmq:
    image: rabbitmq:4.3.0-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
  
  ibmmq:
    image: jan310/ibm-mqadvanced-server-dev:9.4.5.1-arm64
    container_name: ibmmq
    ports:
      - "1414:1414"   # IBM MQ
      - "9443:9443"   # Management UI (via https)
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
      MQ_APP_PASSWORD: ${IBM_MQ_PASSWORD} # user = app
      MQ_ADMIN_PASSWORD: ${IBM_MQ_PASSWORD} # user = admin
    volumes:
      - ./config.mqsc:/etc/mqm/config.mqsc
