spring:
  application:
    name: xml-json-adapter
  jms:
    cache:
      session-cache-size: 32
    listener:
      min-concurrency: 8
      max-concurrency: 32
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        concurrency: 8
        max-concurrency: 32
        prefetch: 8
  threads:
    virtual:
      enabled: true

ibm:
  mq:
    queue-manager: QM1
    conn-name: localhost(1414)
    channel: DEV.APP.SVRCONN
    user: ${IBM_MQ_USER}
    password: ${IBM_MQ_PASSWORD}
