spring:
  application:
    name: ibmmq-test-client
  threads:
    virtual:
      enabled: true
  ssl:
    bundle:
      jks:
        ibmmq:
          keystore:
            location: file:../certs/clients/ibmmq-test-client/client.p12
            password: changeit
            type: PKCS12
          truststore:
            location: file:../certs/truststore.p12
            password: changeit
            type: PKCS12

ibm:
  mq:
    queue-manager: QM1
    conn-name: localhost(1414)
    channel: MTLS.APP.SVRCONN
    user: app
    password: password
    ssl-bundle: ibmmq
    ssl-cipher-suite: "*TLS12ORHIGHER"
    ssl-peer-name: CN=ibmmq,O=vedoc POC,C=DE
