spring:
  application:
    name: vedoc
  profiles:
    active: web
  mongodb:
    uri: mongodb://mongodb:27017/vedoc?replicaSet=rs0
  rabbitmq:
    host: rabbitmq
    port: 5671
    username: user
    password: password
    ssl:
      enabled: true
      key-store: file:/run/tls/client.p12
      key-store-password: changeit
      key-store-type: PKCS12
      trust-store: file:/run/tls/truststore.p12
      trust-store-password: changeit
      trust-store-type: PKCS12
      validate-server-certificate: true
      verify-hostname: true
    listener:
      simple:
        concurrency: 8
        max-concurrency: 32
        prefetch: 8
  threads:
    virtual:
      enabled: true

ibm:
  cos:
    endpoint: ${IBM_COS_ENDPOINT}
    location: ${IBM_COS_LOCATION}
    bucket: ${IBM_COS_BUCKET}
    api-key: ${IBM_COS_API_KEY}
    service-instance-id: ${IBM_COS_SERVICE_INSTANCE_ID}

---
spring:
  config:
    activate:
      on-profile: "!web"
  main:
    web-application-type: none
