spring:
  application:
    name: vedoc
  mongodb:
    uri: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@localhost:27017/vedoc?authSource=admin
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        concurrency: 8
        max-concurrency: 32
        prefetch: 8
  threads:
    virtual:
      enabled: true

ibm:
  cos:
    endpoint: ${IBM_COS_ENDPOINT}
    location: ${IBM_COS_LOCATION}
    bucket: ${IBM_COS_BUCKET}
    api-key: ${IBM_COS_API_KEY}
    service-instance-id: ${IBM_COS_SERVICE_INSTANCE_ID}
